driver:
  name: docker
  memory: 2G
  require_chef_omnibus: false

transport:
  name: exec

provisioner:
  name: 'salt_solo'
  salt_bootstrap_url: 'https://github.com/saltstack/salt-bootstrap/releases/latest/download/bootstrap-salt.sh'
  salt_bootstrap_options: -x python3
  salt_minion_extra_config:
    master: '127.0.0.1'
    color: False

driver_config:
  bootstrap: pip

platforms:
  - name: ubuntu-22.04
    driver_config:
      image: ubuntu:22.04
      provision_command:
        - apt-get update
        - DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends wget curl unzip tar mc apt-utils ca-certificates gnupg python3 python3-pip
        - mkdir -p /tmp/kitchen
        - update-alternatives --install /usr/bin/python python /usr/bin/python3 10

  - name: rockylinux-9-minimal
    driver_config:
      image: rockylinux:9
      provision_command:
        - yum install -y wget curl unzip tar mc ca-certificates gnupg2 python3 python3-pip
        - alternatives --set python /usr/bin/python3
        - mkdir -p /tmp/kitchen

suites:
  - name: base
    provisioner:
      formula: base
      state_top:
        base:
          "*":
            - base

  - name: terraform
    provisioner:
      formula: terraform
      state_top:
        base:
          "*":
            - terraform