{%- from 'base/settings.jinja' import base with context %}
" {{ salt['pillar.get']('salt_banner','Managed by salt') }}

syntax enable
set nocompatible
set bs=indent,eol,start
set history=100
set laststatus=2
set ruler
set viminfo='20,"500
syntax on
set hlsearch
set nowrap
set bg=dark
set tabstop=2
